spring.application.name=ERP

# ---------------> no olvides cambiar al desplegado antes de hacer push <----------------

# LOCAL
#spring.datasource.url=jdbc:sqlserver://localhost;instanceName=SQLEXPRESS;databaseName=ERP_DEV;encrypt=true;trustServerCertificate=true
#spring.datasource.username=ERP
#spring.datasource.password=motitasegunda2

# DESPLEGADO
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:sqlserver://cosmos-oli.database.windows.net:1433;database=ERP_DEV;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:ghostrider@cosmos-oli}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:cosmos-123}

spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:com.microsoft.sqlserver.jdbc.SQLServerDriver}
server.port=${SERVER_PORT:8080}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:none}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.dialect=${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT:org.hibernate.dialect.SQLServerDialect}

security.jwt.secret=${SECURITY_JWT_SECRET:8ae189108dc2833b4d4fd3f2fa383bb2a7c2bde0335b031f3b745495e9c31ec9}
security.jwt.issuer=${SECURITY_JWT_ISSUER:iam-service}
security.jwt.expiration-seconds=${SECURITY_JWT_EXPIRATION_SECONDS:180000}

# Roles provisionales

organizations.authz.allowed-roles.create-branch=${ORG_AUTHZ_ALLOWED_ROLES_CREATE_BRANCH:1}